
name: nodejs-ci

on:
  push:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  nodejs-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use matching NodeJS version
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true

    - name: Install modules and run gulp build
      run: npm ci

    - name: Test
      run: npm run test

    - name: Report results
      uses: IgnusG/jest-report-action@v2.3.3
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}